# Generated by Django 5.1.2 on 2025-10-07 13:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="The job title (e.g., 'Senior Python Developer')", max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the role.')),
                ('location', models.CharField(help_text="City, State, or 'Remote'", max_length=100)),
                ('job_type', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('CT', 'Contract'), ('IT', 'Internship')], default='FT', help_text='Type of employment.', max_length=2)),
                ('min_salary', models.IntegerField(blank=True, help_text='Minimum expected annual salary (optional).', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_salary', models.IntegerField(blank=True, help_text='Maximum expected annual salary (optional).', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('requirements', models.TextField(help_text='Key skills and qualifications required (e.g., technologies, education).')),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this job currently accepting applications?')),
                ('company', models.ForeignKey(help_text='The company that posted this job.', on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='home.companyprofile')),
            ],
            options={
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('INTERVIEW', 'Interview Scheduled'), ('OFFER', 'Offer Extended'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current status of the application.', max_length=10)),
                ('candidate', models.ForeignKey(help_text='The candidate submitting the application.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='home.candidateprofile')),
                ('job', models.ForeignKey(help_text='The job posting the candidate is applying for.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='home.jobposting')),
            ],
            options={
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-application_date'],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
