# Generated by Django 5.1.2 on 2025-10-15 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_jobposting_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(help_text='Candidate who uploaded this resume.', on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='home.candidateprofile')),
            ],
            options={
                'verbose_name': 'Candidate Resume',
                'verbose_name_plural': 'Candidate Resumes',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
