# Generated by Django 5.1.2 on 2025-11-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_candidateresume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of birth of the applicant.', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='education',
            field=models.CharField(blank=True, help_text='Highest education qualification.', max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(default='', help_text="Applicant's email address.", max_length=254),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected salary in BDT.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience',
            field=models.CharField(blank=True, help_text='Years of experience (e.g., 2 years, 6 months).', max_length=50),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='full_name',
            field=models.CharField(default='', help_text='Full name of the applicant.', max_length=100),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(default='', help_text="Applicant's phone number.", max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='portfolio',
            field=models.URLField(blank=True, help_text='Link to LinkedIn or portfolio (optional).'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, help_text='Uploaded resume file.', null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skills',
            field=models.TextField(blank=True, help_text='Skills or technologies known by the applicant.'),
        ),
    ]
